config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  constraints Clearance::Constraints::SignedIn.new do
    root "welcome#dashboard"
  end

  constraints Clearance::Constraints::SignedOut.new do
    root 'welcome#index'
  end

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  # routes for user
  resources :users

  # routes for sessions
  get "/sessions/new" => "sessions#new", as: "sign_in"
  post "/sessions" => "sessions#create"
  delete "sessions" => "sessions#destroy", as: "sign_out"

  # route for facebook callback, for when the user has already signed_in from fb and are returning from fb
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  # routes for pending matches
  resources :users, only: [] do
    resources :pendings, only: [:index, :new, :create, :show, :destroy]
  end

  # route for creating match_statuses
  resources :pendings, only: [] do
    resources :match_statuses, only: [:create]
  end

  #routes for matches
  resources :users, only: [] do
    resources :matches, only: [:index, :show]
  end

  #routes for messages and confirmed_activities
  resources :matches, only: [] do
    resources :messages, only: [:create]
    resources :confirmed_activities, only: [:create, :destroy]
    post "/confirmed_activities/:id" => "confirmed_activities#confirm"
  end

  # Serve websocket cable requests in-process
  mount ActionCable.server => "/cable"

  # these are routes from clearance
  # resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  # resource :session, controller: "clearance/sessions", only: [:create]

  # resources :users, controller: "clearance/users", only: [:create] do
  #   resource :password,
  #     controller: "clearance/passwords",
  #     only: [:create, :edit, :update]
  # end

  # get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  # delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"
end

app/models/pending.rb
class Pending < ApplicationRecord
  belongs_to :user
  belongs_to :activity

  # when 'waiting', it means that the user is still waiting for a confirmed_activity
  # when 'successful', it means that the user has already got a confirmed_activity for that particular pending
  enum status: [:waiting, :successful]

  #validations
  validates :activity_id, :user_id, :city, :datetime, :status, presence: true

  # accessor for new pending form
  attr_accessor :date, :time

  # since we've got 2 pending table joins in matches table, we need to create a method to get a pending's matches
  def potential_matches
    all_unavailable_id = get_unavailable_matches_id

    all_similar_pendings = Pending.joins(:user).where(
      activity_id: self.activity_id,
      city: self.city,
      status: "waiting",
      # user attributes
      users: {
        age_range: self.user.age_range,
        stamina: self.user.stamina,
        strength: self.user.strength,
        agility: self.user.agility
      }
    )

    all_similar_pendings = filter_by_date_only(all_similar_pendings)

    # return pendings that are available and not the user's own pendings
    return all_similar_pendings.where.not(id: all_unavailable_id, user_id: self.user_id)
  end

  def delete_related_matches_matchstatuses
    # delete all related matchstatus to this pending
    MatchStatus.where(pending_viewer_id: self.id).delete_all
    MatchStatus.where(pending_viewed_id: self.id).delete_all

    # delete all related matches to this pending
    Match.where(user1_pending_id: self.id).delete_all
    Match.where(user2_pending_id: self.id).delete_all
  end

  private

  def get_unavailable_matches_id
    responded_by_user = MatchStatus.where(pending_viewer_id: self.id).pluck(:pending_viewed_id)
    declined_by_others = MatchStatus.where(pending_viewed_id: self.id, status: :"declined").pluck(:pending_viewer_id)

    declined_by_others.each do |id|
      unless id.include?(responded_by_user)
        responded_by_user << id
      end
    end

    return responded_by_user
  end

  def filter_by_date_only(pendings)
    same_date = []

    pendings.each do |pending|
      p_date = pending.datetime.localtime
      s_date = self.datetime.localtime

      if p_date.year == s_date.year && p_date.month == s_date.month && p_date.day == s_date.day
        same_date << pending.id
      end
    end

    Pending.where(id: same_date)

  end

end

app/controllers/pending_controller.rb
class PendingController < ApplicationController
  def new
    @pending = Pending.new
  end

  def create
    @pending = Pending.new(pending_params)

    if @pending
      redirect_to pending_path(@pending)
    else
      redirect_to new_pending_path
    end

  end

  def show
  end

  def destroy
  end

  private

  def pending_params
    return_hash = params.require(:pending).permit(:city, :datetime)
    # if the input activity is a long string, and not a number
    if params[:pending][:activity].to_i == 0
      find_if_exists = Activity.where(name: params[:pending][:activity])

      # if the user specifies an activity that already exists
      if find_if_exists == []
        new_activity = Activity.create(name: params[:pending][:activity].capitalize)
        return_hash[:activity_id] = new_activity.id
      else
        return_hash[:activity_id] = find_if_exists[0].id
      end

    else
      return_hash[:activity_id] = params[:pending][:activity].to_i
    end

  end

end

app/controllers/pendings_controller.rb
class PendingsController < ApplicationController
  before_action :require_login
  before_action :require_user_details

  def index
    current_user_authorised?(params[:user_id], root_path)

    @pendings = Pending.where(user_id: params[:user_id], status: "waiting").order('created_at desc')
  end

  def new
    current_user_authorised?(params[:user_id], root_path)

    @pending = Pending.new
  end

  def create
    current_user_authorised?(params[:user_id], root_path)

    pending_attrs = pending_params

    # condiiton for when the user doesn't specify an other activity
    if !pending_attrs
      flash[:danger] = "You need to specify an activity!"
      return redirect_to new_user_pending_path(user_id: current_user.id)
    end

    @pending = Pending.new(pending_attrs)
    @pending.status = "waiting"
    @pending.user_id = current_user.id

    if @pending.save
      redirect_to user_pending_path(user_id: current_user.id, id: @pending)
    else
      redirect_to new_user_pending_path(user_id: current_user.id)
    end

  end

  def show
    current_user_authorised?(params[:user_id], root_path)

    @pending = Pending.find(params[:id])
  end

  def destroy
    current_user_authorised?(params[:user_id], root_path)

    pending = Pending.find(params[:id])

    pending.delete_related_matches_matchstatuses
    pending.destroy

    redirect_to user_path(current_user)
  end

  private

  def pending_params
    return_hash = params.require(:pending).permit(:city)
    return_hash[:datetime] = get_datetime(params[:pending])

    if params[:pending][:activity_id] == "0"
      # condition for when an other activity is specified or none
      if params[:pending][:activity] != ""
        activity_id = Activity.get_id(params[:pending][:activity])
        return_hash[:activity_id] = activity_id
      else
        return false
      end
    else
      return_hash[:activity_id] = params[:pending][:activity_id].to_i
    end

    return return_hash
  end
end

app/helpers/pending_helper.rb
module PendingHelper
end

app/helpers/pendings_helper.rb
module PendingsHelper
end

app/views/pendings/index.html.erb
<%= render partial: "layouts/dbsidebar" %>

<div class="dashbox-pend">
    <div class="container">
        <div class="row">
          <% @pendings.each do |pending| %>
            <%= link_to user_pending_path(current_user, pending) do %>
              <div class="col-sm-3" style="padding-left:8px; padding-right:8px; ">
                <div class="item well">
                  <div class="item-img">
                    <%= image_tag "img-seed/seed-img#{rand(1..15)}.jpg", width: "100%", style: "position: relative; bottom: 25%" %>
                  </div>
                  <div class="row">
                  <div class="col-sm-2" style="width: 65%; padding-right: 0px; padding-left: 15px;">
                    <div class="item-content" style="border-right: 1px solid #898989; width: 85%; margin-left: 15px;">
                      <p style="margin-top: 10px; font-size: 20px;"><%= pending.activity.name %></p>
                      <p style="padding-top: 7px;"><%= pending.city %></p>
                      <% if Match.where(user1_pending_id: pending.id).or(Match.where(user2_pending_id: pending.id)) == [] %>
                        <p style="padding-top: 4px; font-weight: bold;">No matches yet</p>
                      <% else %>
                        <p style="padding-top: 4px; font-weight: bold;">Has matches already</p>
                      <% end %>
                    </div>
                  </div>
                  <div class="col-sm-2" style="width: 35%; padding-left: 0;">
                    <div class="item-content" style="margin-left: 0; margin-top: 5px; margin-right: 10px;">
                      <p style="font-size: 30px; text-align: center; margin-bottom: 0;"><%= pending.datetime.localtime.strftime("%d") %></p>
                      <p style="text-align: center; padding-top: 5px;"><%= pending.datetime.localtime.strftime("%b %Y") %></p>
                      <p style="text-align: center; padding-top: 5px;"><%= pending.datetime.localtime.strftime("%I:%M %p") %></p>
                    </div>
                  </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
    </div>
</div>


<!-- <div class="container">
	<div class="row">
		<div class="item well">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid laudantium veritatis expedita optio aperiam modi, odit eius, enim a alias itaque voluptate officiis natus placeat nostrum quasi nobis et iure.</p>
		</div>
		<div class="item well">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique reiciendis ipsum laborum ab enim perspiciatis nesciunt earum fugiat veniam, asperiores cumque fugit maiores quisquam ullam necessitatibus id rem illum. Sit.</p>
		</div>
		<div class="item well">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae cupiditate consectetur reprehenderit voluptatum fugiat, temporibus mollitia dolorem, incidunt rem aperiam, saepe nobis ad fugit officia suscipit commodi dolores inventore reiciendis.Lorem	ipsum dolor sit amet, consectetur adipisicing elit. Accusantium ad sequi odit vel asperiores provident, laborum quam rerum odio iste quia, animi, ratione ab nam facilis tenetur, quod repellat voluptatibus.</p>
		</div>
		<div class="item well">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae cupiditate consectetur reprehenderit voluptatum fugiat</p>
		</div>
		<div class="item well">
			<p>temporibus mollitia dolorem, incidunt rem aperiam, saepe nobis ad fugit officia suscipit commodi dolores inventore reiciendis.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium ad sequi odit vel asperiores provident, laborum quam rerum
			odio iste quia, animi, ratione ab nam facilis tenetur, quod repellat voluptatibus.</p>
		</div>
		<div class="item well">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam quod, beatae natus reiciendis a, vero deserunt sed voluptatibus harum quia odio nobis enim qui libero minus iusto atque labore esse!</p>
		</div>
		<div class="item well">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus voluptates error sequi ducimus aperiam! Tempore quos, perferendis aperiam omnis mollitia est vero, ullam ratione eum, laboriosam nisi dolorum ut autem.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus dicta aperiam vel aut, eaque ipsam adipisci magni laudantium molestiae fugit dolor rem iusto modi ratione deleniti ex, nulla libero quis.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum quasi sint eaque, asperiores, nam odio laboriosam tempore cum ad maiores accusantium animi reprehenderit labore expedita. Alias dolorum non, pariatur commodi.</p>
		</div>
		<div class="item well">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio reiciendis est hic, quas, quibusdam neque debitis reprehenderit, beatae cupiditate, accusantium consequatur incidunt. Harum ipsam nisi porro veniam. Magnam, autem, maiores!</p>
		</div>
		<div class="item well">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore aliquid repellendus laborum aspernatur nobis. Consequatur velit quibusdam suscipit aut fugiat beatae, tempora eum non libero maiores reiciendis, quas ab illo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dolores eos expedita provident similique sunt iure. Iusto quasi ipsa impedit? Voluptates vel veniam animi ab excepturi sit. Doloremque, ad eum.</p>
		</div>
		<div class="item well">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, repellat, voluptas. Magnam sit non aut sint, ratione voluptates iusto dicta nisi! A nobis expedita nam distinctio natus nulla. Nisi, harum.</p>
		</div>
	</div>
</div> -->

app/views/pendings/new.html.erb
<%= form_for @pending, url: user_pendings_path(current_user) do |f| %>
  <%= f.text_field :city, placeholder: "City" %>
  <hr>
  <%= f.label "Date and Time" %>
  <%= f.date_field :date, placeholder: "Date", class: "date-field" %>
  <%= f.text_field :time, placeholder: "Time", class: "time-field" %>
  <hr>
  <%= f.select :activity_id do %>
    <% activity_array = Activity.order(:name).all.map { |activity| [activity.name, activity.id] } %>
    <%= options_for_select([['Others', 0]]) %>
    <%= options_for_select(activity_array) %>
  <% end %>
  <%= f.text_field :activity, placeholder: "If selected 'Other', please specify" %>
  <%= f.submit %>

<% end %>

app/views/pendings/show.html.erb
<div class="page-color"></div>
<div class="page-content">
  <div class="show-pending-container">
    <br><br><br>
    <div class="panel show-pending-panel">
      <div class="panel-body">
        <h2>YOUR PENDING DETAILS</h2>  
        <table class="">
          <tr>
            <td class="pending-attr">Activity:</td>
            <td class="pending-details"><%= @pending.activity.name %></td>
            <td class="pending-attr">Date:</td>
            <td class="pending-details"><%= @pending.datetime.localtime.strftime("%A, %d %b %Y") %></td>  
          </tr>
          <tr>
            <td class="pending-attr">City:</td>
            <td class="pending-details"><%= @pending.city %></td>
            <td class="pending-attr">Time:</td>
            <td class="pending-details"><%= @pending.datetime.localtime.strftime("%I:%M %p") %></td>
          </tr>
        </table>
      </div>
    </div>
    
    <div class="potential-matches">
      <% if @pending.potential_matches != [] %>
        <h4>AVAILABLE MATCHES</h4>
        <div class="all-matches-panels" style="position: relative">
          <% @pending.potential_matches.each do |potential_match| %>
            <div class="panel potential-match-panel panel-<%= potential_match.id %>">
              <div class="panel-body">
                <div class="row">
                  <div class="col-md-3">
                    <% if potential_match.user.avatar? %>
                      <%= image_tag(potential_match.user.avatar.medium_avatar.url) %>
                    <% else %>
                      <%= image_tag "default_profile.jpg" %>
                    <% end %>
                  </div>
                  <div class="col-md-5">
                    <h2>
                      <% if potential_match.user.name %>
                        <%= potential_match.user.name %>
                      <% else %>
                        No Name                
                      <% end %>
                    </h2>
                    <h5> from <%= potential_match.user.city %>, <%= potential_match.user.state %>, <%= potential_match.user.country %></h5>
                    <table>
                      <tr>
                        <td>Available on</td>
                      </tr>
                      <tr>
                        <td class="pending-details"><%= potential_match.datetime.localtime.strftime("%d %b %Y, %I:%M %p") %></td>
                      </tr>
                    </table>
                  </div>
                  <div class="col-md-4">
                    <table>
                      <tr>
                        <td>
                          <%= button_to "Accept", pending_match_statuses_path(potential_match), method: :post, remote: true,
                                params: { status: "accepted",
                                          pending_viewer_id: @pending.id,
                                          pending_viewed_id: potential_match.id },
                                class: "btn btn-default btn-lg accept-btn"
                          %>
                        </td>
                        <td>
                          <%= button_to "Decline", pending_match_statuses_path(potential_match), method: :post, remote: true,
                                params: { status: "declined",
                                          pending_viewer_id: @pending.id,
                                          pending_viewed_id: potential_match.id },
                                class: "btn btn-default btn-lg decline-btn"
                          %>
                        </td>
                      </tr>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% else %>
        <div class="no-pending-msg">
          <h4>No available matches. Please try again later.</h4>
        </div>
      <% end %>
    </div>
  </div>
</div>