config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  constraints Clearance::Constraints::SignedIn.new do
    root "welcome#dashboard"
  end

  constraints Clearance::Constraints::SignedOut.new do
    root 'welcome#index'
  end

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  # routes for user
  resources :users

  # routes for sessions
  get "/sessions/new" => "sessions#new", as: "sign_in"
  post "/sessions" => "sessions#create"
  delete "sessions" => "sessions#destroy", as: "sign_out"

  # route for facebook callback, for when the user has already signed_in from fb and are returning from fb
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  # routes for pending matches
  resources :users, only: [] do
    resources :pendings, only: [:index, :new, :create, :show, :destroy]
  end

  # route for creating match_statuses
  resources :pendings, only: [] do
    resources :match_statuses, only: [:create]
  end

  #routes for matches
  resources :users, only: [] do
    resources :matches, only: [:index, :show]
  end

  #routes for messages and confirmed_activities
  resources :matches, only: [] do
    resources :messages, only: [:create]
    resources :confirmed_activities, only: [:create, :destroy]
    post "/confirmed_activities/:id" => "confirmed_activities#confirm"
  end

  # Serve websocket cable requests in-process
  mount ActionCable.server => "/cable"

  # these are routes from clearance
  # resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  # resource :session, controller: "clearance/sessions", only: [:create]

  # resources :users, controller: "clearance/users", only: [:create] do
  #   resource :password,
  #     controller: "clearance/passwords",
  #     only: [:create, :edit, :update]
  # end

  # get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  # delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  enum age_range: ["0-18", "19-29", "30-39", "40-49", "50-59", "60-69", "70-79", "80+"]

  validates :stamina, :strength, :agility, inclusion: { in: [nil, 1, 2, 3, 4, 5], message: "invalid values." }

  has_many :authentications
  has_many :pendings
  has_many :confirmed_activities
  has_many :messages

  mount_uploader :avatar, AvatarUploader

  def self.create_with_auth_and_hash(authentication, auth_hash)
    def password_optional?
      true
    end

    user = User.create!(name: auth_hash[:info][:name], email: auth_hash[:info][:email])

    avatar_url = auth_hash[:info][:image].gsub("http://", "https://") + "?width=1000&height=1000"
    user.remote_avatar_url = avatar_url
    user.save

    user.authentications << (authentication)

    def password_optional?
      true
    end
    return user
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def has_nil_attributes
    !self.encrypted_password || !self.name || !self.city || !self.state || !self.country || !self.age_range || !self.strength || !self.stamina || !self.agility
  end

  def has_no_password
    if self.encrypted_password == nil
      return true
    else
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  before_action :require_login
  skip_before_action :require_login, only: [:new, :create]
  before_action :require_user_details
  skip_before_action :require_user_details, only: [:new, :create, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(new_user_params)

    if @user.save
      sign_in(@user)
      UserMailer.welcome_email(@user).deliver_now
      flash[:success] = "healthapp account has been successfully created"
      redirect_to root_path
    else
      render 'users/new'
      flash[:danger] = "error in creation of account"
    end
  end

  def show
    current_user_authorised?(params[:id], root_path)

    @user = User.find(params[:id])
  end

  def edit
    current_user_authorised?(params[:id], root_path)

    @user = User.find(params[:id])

    if @user.has_no_password
      flash[:danger] = "You need to have a password"
    end
  end

  def update
    current_user_authorised?(params[:id], root_path)

    @user = User.find(params[:id])

    update_hash = update_user_params

    # if update_hash == false due to passwords that do not match
    unless update_hash
      flash[:danger] = "Passwords do not match!"
      return redirect_to edit_user_path(params[:id])
    end

    # if remove_avatar is true
    if update_hash[:remove_avatar] == "1"
      @user.remove_avatar!
      @user.save
    end

    if @user.update(update_hash)
      flash[:success] = "Update successful"
      redirect_to root_path
    else
      flash[:danger] = "Update unsuccessful"
      redirect_to edit_user_path(@user)
    end

  end

  def destroy
    current_user_authorised?(params[:id], root_path)

		user = User.find_by_id(params[:id])
		sign_out
		user.authentications.delete_all
		user.destroy
		redirect_to root_path
  end

  private

  def new_user_params
    params.require(:user).permit(:email, :password, :name, :city, :state, :country, :age_range, :stamina, :strength, :agility, :additional_health_problems, :weekly_activity_hours, :avatar)
  end

  def update_user_params
    attr = params.require(:user).permit(:email, :name, :city, :state, :country, :stamina, :strength, :agility, :additional_health_problems, :weekly_activity_hours, :avatar, :remove_avatar)

    # convert string to integers for these attributes
    attr[:age_range] = params[:user][:age_range].to_i
    attr[:stamina] = attr[:stamina].to_i
    attr[:strength] = attr[:strength].to_i
    attr[:agility] = attr[:agility].to_i

    # check if passwords are the same if the user fills up the password form
    same_passwords = params[:user][:password] == params[:user][:retype_password]

    if params[:user][:password] != ""
      if same_passwords
        attr[:password] = params[:user][:password]
      else
        return false
      end
    end

    return attr

  end
end

app/views/users/edit.html.erb
<div class="jumbotron edit_user_bg">
  <div class="container-fluid" >
    <span style="font-size:30px;cursor:pointer" id="f-logo"><%= link_to image_tag("f-clear_bg.png"), root_path%></span>

    <div id="main">
      <h1 id="edit_profile">Edit Profile</h1>

      <div class="container" >
        <div id="editbox"  >
          <%= form_for @user, id: "edit-user", url: user_path(@user), method: :patch do |f| %>
            <%= image_tag(@user.avatar.large_avatar.url, width: "50%", height: "auto") if @user.avatar? %>
            <%= f.file_field :avatar %>
            <%= f.check_box :remove_avatar, id: "avatar-checkbox" %>Remove Avatar
            <hr>
            <%= f.text_field :name, placeholder: "Name", class: "input pass" %>
            <%= f.email_field :email, placeholder: "Email", class: "input pass" %>
            <%= f.password_field :password, placeholder: "Password", class: "input pass" %>
            <%= f.password_field :retype_password, placeholder: "Re-type Password", class: "input pass" %>
            <hr>
            <%= f.text_field :city, placeholder: "City", class: "input pass" %>
            <%= f.text_field :state, placeholder: "State", class: "input pass" %>
            <%= f.text_field :country, placeholder: "Country", class: "input pass" %>
            <hr>
            <%= f.label "Targeted hours of exercise per week" %>
            <%= f.number_field :weekly_activity_hours, class: "input pass" %>
            <%= f.label "Age Range" %>
            <%= f.select :age_range, User.age_ranges, class: "input pass" %>
            <hr>
            <% rating_range = [[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]] %>
            <%= f.label "Stamina" %>
            <%= f.select :stamina, rating_range, class: "input pass" %>
            <%= f.label "Strength" %>
            <%= f.select :strength, rating_range, class: "input pass" %>
            <%= f.label "Agility" %>
            <%= f.select :agility, rating_range, class: "input pass" %>
            <hr>
            <%= f.text_area :additional_health_problems, placeholder: "additional health problems", class: "input pass" %>
            <hr>
            <%= f.submit "Enter", class: "submitButton" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <div class="sidebar-logo">
    <%= image_tag("fitbuds-clear_bg-new-grey.png")%>
  </div>
  <%= link_to "Sign In", sign_in_path %>
  <%= link_to "Back to Main", root_path %>
</div>

<div class="jumbotron signup_bg">
  <div class="container-fluid" >
    <span style="font-size:30px;cursor:pointer" onclick="openNav()" id="f-logo"><%= image_tag("f-clear_bg.png") %></span>
    <div id="main">
      <h2 id="signup-text">Signup now and find your Fitbuds</h2>
      <div id="signup-box">
        <%= link_to image_tag("fitbuds-clear_bg-new-grey.png"), root_path%>
        <%= form_for @user, id: "signup", url: users_path do |f| %>
          <%= f.email_field :email, placeholder: "Email", type: "email", class: "input pass" %>
          <%= f.password_field :password, placeholder: "Password", type: "password", class: "input pass" %>
          <%= f.submit "Sign Up", class: "inputButton" %>
        <% end %>
      </div>
    </div>
  </div>
</div>



<script>
function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
    document.getElementById("main").style.marginLeft = "250px";
    // document.getElementById("main").fadeOut();
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
    document.getElementById("main").style.marginLeft= "0";
    // document.getElementById("main").fadeIn();
}
</script>