config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  constraints Clearance::Constraints::SignedIn.new do
    root "welcome#dashboard"
  end

  constraints Clearance::Constraints::SignedOut.new do
    root 'welcome#index'
  end

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  # routes for user
  resources :users

  # routes for sessions
  get "/sessions/new" => "sessions#new", as: "sign_in"
  post "/sessions" => "sessions#create"
  delete "sessions" => "sessions#destroy", as: "sign_out"

  # route for facebook callback, for when the user has already signed_in from fb and are returning from fb
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  # routes for pending matches
  resources :users, only: [] do
    resources :pendings, only: [:index, :new, :create, :show, :destroy]
  end

  # route for creating match_statuses
  resources :pendings, only: [] do
    resources :match_statuses, only: [:create]
  end

  #routes for matches
  resources :users, only: [] do
    resources :matches, only: [:index, :show]
  end

  #routes for messages and confirmed_activities
  resources :matches, only: [] do
    resources :messages, only: [:create]
    resources :confirmed_activities, only: [:create, :destroy]
    post "/confirmed_activities/:id" => "confirmed_activities#confirm"
  end

  # Serve websocket cable requests in-process
  mount ActionCable.server => "/cable"

  # these are routes from clearance
  # resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  # resource :session, controller: "clearance/sessions", only: [:create]

  # resources :users, controller: "clearance/users", only: [:create] do
  #   resource :password,
  #     controller: "clearance/passwords",
  #     only: [:create, :edit, :update]
  # end

  # get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  # delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"
end

app/models/match.rb
class Match < ApplicationRecord
  validates :user1_id, :user2_id, :user1_pending_id, :user2_pending_id, presence: true
  validates :user1_pending_id, uniqueness: { scope: :user2_pending_id }
  validate :reversed_unique_ids

  has_many :messages
  has_one :confirmed_activity

  def user1
    User.find_by_id(self.user1_id)
  end

  def user2
    User.find_by_id(self.user2_id)
  end

  def user1_pending
    Pending.find_by_id(self.user1_pending_id)
  end

  def user2_pending
    Pending.find_by_id(self.user2_pending_id)
  end

  def reversed_unique_ids
    if Match.find_by(user1_pending_id: user2_pending_id, user2_pending_id: user1_pending_id)
      errors.add(user1_pending_id, "Match already exists for this particular combinaton of pendings")
    end
  end

  def mark_both_pendings_success
    user1_pending.update(status: "successful")
    user2_pending.update(status: "successful")
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :require_login
  before_action :require_user_details

  def index
    current_user_authorised?(params[:user_id], root_path)

    @matches = Match.where(user1_id: params[:user_id]).or(Match.where(user2_id: params[:user_id]))

    if @matches != []
      # order the matches based on created_at
      @matches = @matches.order('created_at desc')
    else
      flash[:danger] = "No matches available"
      redirect_to root_path
    end
  end

  def show
    current_user_authorised?(params[:user_id], root_path)

    match = Match.find_by_id(params[:id])

    if current_user_authorised_for_match?(match)
      @match = match
      @confirmed_activity = ConfirmedActivity.new
    end
  end

end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/index.html.erb
<%= render partial: "layouts/dbsidebar" %>
<div class="body-match"></div>
<div class="dashbox-match">
  <div class="container">
    <div class="row">
      <% @matches.each do |match| %>
        <% if match.user1 == current_user %>
          <% other_user = match.user2 %>
          <% pending = match.user1_pending %>
        <% else %>
          <% other_user = match.user1 %>
          <% pending = match.user2_pending %>
        <% end %>
        <%= link_to user_match_path(current_user, match) do %>
          <div class="col-sm-3" style="padding-left: 5px;">
            <div class="well" style="height: 350px;">
              <div class="profile-img" style="height: 130px;">
                <% if other_user.avatar? %>
                  <%= image_tag other_user.avatar.url %>
                <% else %>
                  <%= image_tag "default_profile.jpg", width: "100%", height: "auto"%>
                  <span class="sr-only"></span>
                <% end %>
              </div>
              <div style="text-align: center; margin-top: 10px;margin-bottom: 5px; font-weight: 700; font-size: 15px; text-transform: capitalize"><%= other_user.name %></div>
              <div style="text-align: center; margin-bottom: 10px; color: #fff; background: #258f9f; width: 100px; border-radius: 10px; margin-left: 85px;"><%= pending.activity.name %> </div>
              <div class="item-match" style="margin-bottom: 15px; margin-left: auto; margin-right: auto">
                <table class="confirm-status-indi">
                  <tr>
                    <td class="confirm-indi">
                      <p>
                        <% if match.confirmed_activity && match.confirmed_activity.user1_confirm && match.confirmed_activity.user2_confirm %> 
                          <i class="material-icons md-18" style="vertical-align:middle; font-size: 15px; line-height: 13px; padding-right:2px; color: #A9CF54;">fiber_manual_record</i>
                        <% else %>
                          <i class="material-icons md-18" style="vertical-align:middle; font-size: 15px; line-height: 13px; padding-right:2px; color: #ccc;">fiber_manual_record</i>
                        <% end %>
                        Confirm
                      </p>
                    </td>
                    <td class="unconfirm-indi">
                      <p>
                        <% if !match.confirmed_activity || !match.confirmed_activity.user1_confirm || !match.confirmed_activity.user2_confirm %> 
                          <i class="material-icons md-18" style="vertical-align:middle; font-size: 15px; line-height: 13px; padding-right:2px; color: #f1433f;">fiber_manual_record</i>
                        <% else %>
                          <i class="material-icons md-18" style="vertical-align:middle; font-size: 15px; line-height: 13px; padding-right:2px; color: #ccc;">fiber_manual_record</i>
                        <% end %>
                        Waiting
                      </p>
                    </td>
                  </tr>
                </table>
              </div>
              <table class="index-matches">
               <tr>
                 <td class="match-attr">City</td>
                 <td class="match-details"><%= pending.city %></td>
               </tr>
               <tr>
                 <td class="match-attr">Date</td>
                 <td class="match-details"><%= pending.datetime.localtime.strftime("%d %b %Y") %></td>
               </tr>
              </table>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<div>

app/views/matches/show.html.erb
<%= render partial: "layouts/dbsidebar" %>

<div class="page-content">
  <div class="show-match-container">
    
    <% if current_user == @match.user1 %>
      <% you = @match.user1 %>
      <% them = @match.user2 %>
      <% your_pending = @match.user1_pending %>
      <% their_pending = @match.user2_pending %>
    <% else %>
      <% you = @match.user2 %>
      <% them = @match.user1 %>
      <% your_pending = @match.user2_pending %>
      <% their_pending = @match.user1_pending %>
    <% end %>

      <br>
      <div class="pending-info">
        <h4>YOUR PENDING FOR THIS MATCH</h4>
        <hr class="match-hr">
        <table>
          <tr>
            <td class="pending-attr"><p>Activity:</p></td>
            <td class="pending-details"><p><%= your_pending.activity.name %></p></td>
            <td class="pending-attr"><p>Date: </p></td>
            <td class="pending-details"><p><%= your_pending.datetime.localtime.strftime("%A, %d %b %Y") %></p></td>
          </tr>
          <tr>
            <td class="pending-attr"><p>City:</p></td>
            <td class="pending-details"><p><%= your_pending.city %></p></td>
            <td class="pending-attr"><p>Time:</p></td>
            <td class="pending-details"><p><%= your_pending.datetime.localtime.strftime("%I:%M %p") %></p></td>
          </tr>
        </table>
      </div>

      <div class="row match-other-row">
        <div class="col-md-4">
          <% if them.avatar? %>
            <%= image_tag them.avatar.large_avatar.url %>
          <% else %>
            <%= image_tag "default_profile.jpg" %>
          <% end %>
            
        </div>

        <div class="col-md-8">
          <div class="other-user-details">
            <h2><%= them.name %></h2>
            <h4>from <%= them.city %>, <%= them.state %>, <%= them.country %></h4>
            <p><%= them.email %></p>
            <br>
            <table class="user-attr-table">
              <tr>
                <td>Stamina:</td>
                <td class="attr-value"><%= them.stamina %></td>
                <td>Strength:</td>
                <td class="attr-value"><%= them.strength %></td>
                <td>Agility:</td>
                <td class="attr-value"><%= them.agility %></td>
              </tr>
            </table>
            <br>
            <hr class="match-hr">
            <h4 class="other-pending-title">Their Pending details</h4>
            <table class="other-pending-table">
              <tr>
                <td class="pending-attr"><p>Activity:</p></td>
                <td class="pending-details"><p><%= their_pending.activity.name %></p></td>
                <td class="pending-attr"><p>Date: </p></td>
                <td class="pending-details"><p><%= their_pending.datetime.localtime.strftime("%A, %d %b %Y") %></p></td>
              </tr>
              <tr>
                <td class="pending-attr"><p>City:</p></td>
                <td class="pending-details"><p><%= their_pending.city %></p></td>
                <td class="pending-attr"><p>Time:</p></td>
                <td class="pending-details"><p><%= their_pending.datetime.localtime.strftime("%I:%M %p") %></p></td>
              </tr>
            </table>
            
          </div>
        </div>
      </div>
    
    <div class="row chat-form-row">
      <div class="col-md-6 chat-col">
        <h4>CHAT</h4>
        <% if current_user == @match.user1 %>
          <div class="chatbox" data-match-id="<%= @match.id %>" data-self="<%= @match.user1.id %>" data-other="<%= @match.user2.id %>">
        <% else %>
          <div class="chatbox" data-match-id="<%= @match.id %>" data-self="<%= @match.user2.id %>" data-other="<%= @match.user1.id %>">
        <% end %>
          <ol class="chat">
            <% @match.messages.order('created_at').each do |msg| %>
              <% if msg.user.id == current_user.id %>
                <li class="self">
              <% else %>
                <li class="other">
              <% end %>
                  <div class="msg">
                    <p><%= msg.content %></p>
                  </div>
                </li>
            <% end %>
          </ol>

          <div class="reply-msg">
            <%= form_for :message, url: match_messages_path(@match), remote: true do |f| %>
              <%= f.text_field :content, placeholder: "Message", class: "reply-input" %>
              <%= f.submit "Send" %>
            <% end %>
          </div>
        </div>      
      </div>

      <div class="col-md-5 confirmed-activity-col">
        <h4>CONFIRM THE ACTIVITY</h4>
        <% activity = @match.confirmed_activity %>
        <% if activity %>
          <div class="panel">
            <div class="panel-body">
              <table class="confirm-details">
                <tr>
                  <td class="confirm-attr"><p>Activity</p></td>
                  <td><p><%= activity.activity.name %></p></td>
                </tr>
                <tr>
                  <td class="confirm-attr"><p>Location</p></td>
                  <td><p><%= activity.location %></p></td>
                </tr>
                <tr>
                  <td class="confirm-attr"><p>Date</p></td>
                  <td><p><%= activity.datetime.localtime.strftime("%A, %d %b %Y") %></p></td>
                </tr>
                <tr>
                  <td class="confirm-attr"><p>Time</p></td>
                  <td><p><%= activity.datetime.localtime.strftime("%I:%M %p") %></p></td>
                </tr>
                <tr>
                  <td class="confirm-attr"><p>Duration</p></td>
                  <td><p><%= activity.duration_in_hours %> hour(s)</p></td>
                </tr>
              </table>
          <!-- conditions for when the user has confirmed/not confirmed -->
          <% if activity.user1_confirm && activity.user2_confirm %>
            <div class="alert alert-success confirm-alert">
              <p class="confirm-message">You've both confirmed this activity!</p>
            </div>
          <% elsif (current_user == @match.user1 && activity.user1_confirm) || (current_user == @match.user2 && activity.user2_confirm) %>
            <div class="alert alert-info confirm-alert">
              <p class="confirm-message">Waiting for other user to confirm!</p>
            </div>
          <% else %>
              <%= button_to "or decline to recreate activity", match_confirmed_activity_path(@match, activity), method: :delete, class: "decline-link" %>
              <p><%= button_to "Confirm", match_confirmed_activity_path(@match, activity), method: :post, class: "btn btn-primary btn-lg confirm-btn" %></p>
          <% end %>
            </div>
          </div>

        <% else %>
          <%= form_for @confirmed_activity, url: match_confirmed_activities_path(@match) do |f| %>
            <!-- for user confirmation based on the current_user -->
            <% if current_user == @match.user1 %>
              <%= f.hidden_field :user1_confirm, value: true %>
            <% else %>
              <%= f.hidden_field :user2_confirm, value: true %>
            <% end %>

            <div class="panel">
              <div class="panel-body">
                <table class="confirm-form">
                  <tr>
                    <td class="confirm-attr"><p>Activity</p></td>
                    <td><p>
                      <%= f.select :activity_id, {}, {}, { class: "form-activity" } do %>
                        <% activity_array = Activity.order(:name).all.map { |activity| [activity.name, activity.id] } %>
                        <%= options_for_select([['Others', 0]]) %>
                        <%= options_for_select(activity_array) %>
                      <% end %>
                      <%= f.text_field :activity, placeholder: "If 'Other', please specify" %>
                    </p></td>
                  </tr>
                  <tr>
                    <td class="confirm-attr"><p>Location</p></td>
                    <td><p>
                      <%= f.text_field :location, placeholder: "Location" %>
                    </p></td>
                  </tr>
                  <tr>
                    <td class="confirm-attr"><p>Date</p></td>
                    <td><p>
                      <%= f.date_field :date, placeholder: "Date", class: "date-field" %>
                    </p></td>
                  </tr>
                  <tr>
                    <td class="confirm-attr"><p>Time</p></td>
                    <td><p>
                      <%= f.text_field :time, placeholder: "Time", class: "time-field" %>
                    </p></td>
                  </tr>
                  <tr>
                    <td class="confirm-attr"><p>Duration</p></td>
                    <td><p>
                      <%= f.number_field :duration_in_hours, placeholder: "Duration" %> <span style="color: #818181;">(in hours)</span>
                    </p></td>
                  </tr>
                </table>
              </div>
            </div>

            <%= f.submit "Confirm", class: "btn btn-primary btn-lg confirm-btn" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>  
</div>