config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  constraints Clearance::Constraints::SignedIn.new do
    root "welcome#dashboard"
  end

  constraints Clearance::Constraints::SignedOut.new do
    root 'welcome#index'
  end

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  # routes for user
  resources :users

  # routes for sessions
  get "/sessions/new" => "sessions#new", as: "sign_in"
  post "/sessions" => "sessions#create"
  delete "sessions" => "sessions#destroy", as: "sign_out"

  # route for facebook callback, for when the user has already signed_in from fb and are returning from fb
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  # routes for pending matches
  resources :users, only: [] do
    resources :pendings, only: [:index, :new, :create, :show, :destroy]
  end

  # route for creating match_statuses
  resources :pendings, only: [] do
    resources :match_statuses, only: [:create]
  end

  #routes for matches
  resources :users, only: [] do
    resources :matches, only: [:index, :show]
  end

  #routes for messages and confirmed_activities
  resources :matches, only: [] do
    resources :messages, only: [:create]
    resources :confirmed_activities, only: [:create, :destroy]
    post "/confirmed_activities/:id" => "confirmed_activities#confirm"
  end

  # Serve websocket cable requests in-process
  mount ActionCable.server => "/cable"

  # these are routes from clearance
  # resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  # resource :session, controller: "clearance/sessions", only: [:create]

  # resources :users, controller: "clearance/users", only: [:create] do
  #   resource :password,
  #     controller: "clearance/passwords",
  #     only: [:create, :edit, :update]
  # end

  # get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  # delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"
end

app/views/layouts/_dbsidebar.html.erb
<!-- topbar -->
<!-- side-navigation -->
<div class="leftbar">
  <div class="leftbar-bg">
    <div class="left-side-container">
      <a href="/"><%= image_tag "fitbuds-clear_bg-new-grey.png", class: "brand", style: "width: 128px; height: 55px;" %></a>
      <div class="user-profile-container" style="border-top: solid 1px rgba(0, 0, 0, 0.12)">
        <div class="user-profile clearfix">
          <div class="user-thumb">
            <% if current_user.avatar? %>
              <%= image_tag current_user.avatar.small_avatar.url, width: "70px", height: "70px" %>
            <% else %>
              <%= image_tag "default_profile.jpg", width: "70px", height: "70px" %>
            <% end %>
          </div>
          <div class="user-info">
            <ul style="padding-left: 0;margin-bottom: 0; font-weight: 300; text-align: left;  ">
              <li style="text-transform: capitalize"><%= current_user.name %></li>
              <li><%= current_user.email %></li>
              <li>
                <a href="<%= edit_user_path(current_user) %>" class="btn btn-default" style="vertical-align: middle;width: 114px; border-radius: 0; height: 30px;">
                  <i class="material-icons md-18" style="vertical-align: middle; font-size: 14px; line-height: 14px; padding-right: 10px; height: 16px;">mode_edit</i>
                  edit
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="user-add-info">
        <ul style="text-transform: capitalize; margin-top: 10px;">
          <li style="float:left; margin-left: 20px; width: 100px; margin-right: 20px;">age</li>
          <li style="text-align: center;"><%= current_user.age_range %></li>
          <li style="float:left; margin-left: 20px; width: 100px;margin-right: 20px;">stamina</li>
          <li style="text-align: center;"><%= current_user.stamina %></li>
          <li style="float:left; margin-left: 20px; width: 100px;margin-right: 20px;">strength</li>
          <li style="text-align: center;"><%= current_user.strength %></li>
          <li style="float:left; margin-left: 20px; width: 100px; margin-right: 20px;">agility</li>
          <li style="text-align: center;"><%= current_user.agility %></li>
        </ul>
        <ul style="text-transform: capitalize; border-top: 1px solid rgba(0, 0, 0, 0.12);">
          <li style="margin-left: 20px; width: 200px; margin-top: 10px;">
            <i class="material-icons md-18" style="vertical-align: middle; margin-right:5px; font-size: 14px; line-height: 12px;">location_city</i>
            City/State/Country
          </li>
          <li style="margin-left: 20px;">
            <i class="material-icons md-18" style="font-size: 15px; margin-right: 5px; margin-right: 5px; line-height: 12px;">label</i>
            <%= current_user.city %>
          </li>
          <li style="margin-left: 20px;">
            <i class="material-icons md-18" style="font-size: 15px; margin-right: 5px; line-height: 12px;">label</i>
            <%= current_user.state %>
          </li>
          <li style="margin-left: 20px;">
            <i class="material-icons md-18" style="vertical-align:middle; font-size: 15px; margin-right: 5px; line-height: 12px;">label</i>
            <%= current_user.country %>
          </li>


          <!-- <li style="float:left; margin-left: 18px; width: 100px; margin-right: 40px;"><i class="material-icons md-18" style="vertical-align: middle; margin-right:7px; font-size: 14px; line-height: 12px;">local_activity</i>Activity</li>
          <li><%= current_user.weekly_activity_hours %></li>
          <li style="float:left; margin-left: 18px; width: 200px; margin-right: 40px;"><i class="material-icons md-18" style="vertical-align: middle; margin-right:7px; font-size: 14px; line-height: 12px;">local_hospital</i>Health Issue</li>
          <li><%= current_user.additional_health_problems %></li> -->

        </ul>
      </div>
      <ul class="list-profile" style="display: block; margin-top: 12px;">
        <li><%= image_tag "icon1.png", width: "13px", height: "13px", style: "margin-right: 5px;" %>
          <%= link_to "waiting/pending", user_pendings_path(current_user), class: "list-style" %>
        </li>
        <li>
          <i class="material-icons md-18" style="vertical-align: middle; margin-right: 5px; font-size: 15px;">recent_actors</i>
          <%= link_to "matches", user_matches_path(current_user), class: "list-style" %>
        </li>
        <!-- <div style="height: 320px;"></div> -->
      </ul>
      <ul class="list-profile logout-btn">
        <li>
          <i class="fa fa-sign-out"></i>
            <%= link_to "logout", sign_out_path, { method: :delete, class: "list-style" } %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Healthapp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css?family=Droid+Serif" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  </head>
  <body>
    <div id="flash">
      <% flash.each do |key, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{key}" %>
      <% end %>
    </div>
    <%= yield %>

  </body>
</html>